apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor 
metadata:
  name: pushgateway-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-pushgateway
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
  endpoints:
  - interval: 15s
    path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - monitoring