apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor 
metadata:
  name: custom-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: test-custom-metrics-service
  endpoints:
  - interval: 15s
    port: web
    path: /metrics
  namespaceSelector:
    matchNames:
    - test-workload